# Generated by Django 3.0.7 on 2020-12-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(null=True)),
                ('client_acknowledgement', models.CharField(default='NA', max_length=3)),
                ('expert_acknowledgement', models.CharField(default='NA', max_length=3)),
                ('chat_room', models.CharField(default='NA', max_length=100)),
                ('client_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Client_Profile')),
                ('expert_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Expert_Profile')),
            ],
        ),
    ]
